version: "3.2"

services:
  dot_share_pg:
    image: postgres:16.2
    container_name: dot_share_pg
    restart: always
    environment:
      POSTGRES_DB: dot_share_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
